[build]
  command = ""
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = ""
  publish = "."

[context.deploy-preview]
  command = ""
  publish = "."
